/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.github.msr;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.15.0)", date = "2023-03-17")
public enum Delimiter implements org.apache.thrift.TEnum {
    Comma(0),
    Pipe(1),
    Tab(2);

    private final int value;

    private Delimiter(int value) {
        this.value = value;
    }

    /**
     * Get the integer value of this enum value, as defined in the Thrift IDL.
     */
    public int getValue() {
        return value;
    }

    /**
     * Find a the enum type by its integer value, as defined in the Thrift IDL.
     * @return null if the value is not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static Delimiter findByValue(int value) {
        switch (value) {
            case 0:
                return Comma;
            case 1:
                return Pipe;
            case 2:
                return Tab;
            default:
                return null;
        }
    }
}